version: '3'

services:
  go-service-stag:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=DOCKER
    env_file:
      - ./local.env
